---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: infra
spec:
  encryptedData:
    password: AgB8AmqMrUtwa4GyA9QIX++CpoKr0bchNSTb/gCGYPJQNsfeRYdHKN8ctrxVHuGVWE+izRsX2DNRv3OYCoPkpWULCnPbr4O37//tfLa/rZVvDiDlgUdhIDqR+ihBQTX3lApSwwzhtPbTgApY/dq1vAgHOiorByC8RzmDysK7MRkffXfXH6oJRgWpEbmK/k61OFx6MZ7MT6NDCZL30AtLcn9SsbPiYTxC1wSh+iYPC5Qh6AqYIBBBy4qYoRlhSIV1lso7tLj5xpaJ0RTSiC1zZQlv2A8jaeEfFOMnEq8PgDAYgCzOLNKq5TJPUZkVMsCczGSaL1CkC/7PtaC0e6U2vdRI4uRpI6/jRcrzWy8fdULYiwIMUJqUuyocLSFdYtz+3VKarNgYBB6z4KGOf3J5Ky7tWIHb20G2kbRMKqrKmNLNrH30k2Y0qsBNDh30QtXu8uErepyVSDVJxOrYUOcr+BC2YB0p5Tw5ovf1nUSJeQV3wPitadSsrX94D514H+D8dG0DhJksWhKGvrHEpoDtCzHYCxUam5+W3FMz2+Qssm1f9Cg72ni47teHbhj9RkCsWYfiWXwtMkQfnuOCDtEkNLhXQk1bw0+MJz24AZHNlcAW9Y3AbfU/Bj4TaTuwCyBZvlHo4MbYr9fhY8A1exRlVh6f5bi9VkkdFt2gQ22NVDi48RvQDXZExRLtoUGnktCFAvH2wl0S/CcH5yG4hC3tLrQ=
    username: AgBzApM4PpGc++sDnSvu2e7poEwN70IrmqopWqZ40wy+0n1OCYk3ObAUtco57Sz7ILCuCEcUXt7KIgxMN1ZS0FaHvS/0tnnb0x1dzzWOCBuj9SwCfAxVjx9wgnJTb6BZxL1Qdgv5mYqwZAeJRlFlto+u0/rMgfduW4rEcIFrYZ7UJptmVv2XeO2qxI4rkl3tRUPAMCJcxDxgnC0wZcSrt/v3HjeknkCHq+P763asS0VAJopYXL9Z6MjeUhGv7EbZRLl6gdGoY6ZumvDEI+k2WdtQ0lFWRosFN/R55o3vyB3V4aDq1nBK1YtrKq9iD2DNYgYK/UqedWcsm/KIzq2/nour3SscJ7TWt+E+/U/4Xc1tkwOaFFMju97RftaVDdYv7wVFknwBj3JsPfqLdd/onSJuOxNpDt80DrCdhVl7G4qtYyPWcKOgJW2Tvo76NmzvcAUMMRXTGzQkAmU/tIndIXRf+fVPnDcOtJnQS0QfTUZwSvUrDpyQjKmEl6WOxBOqLTD1UBnTi+++sZpKbOTkiAK+zMMaWWN3fX1eZUdbOk7v2Mgo83nefiRRNy1BEpYtMXPhal/DURXurph4lV9USyey8W+Fna7MOSeqrQy5w15CEObV/H5APkyk9l6+VoBmjPpaPFWGtLt9FJ3WcohIbx2jw+xlkrx1Ehc1/IgsQK7HtG9c+J+FHbzgjdNntcn29FL+VTSrRw==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: infra
