app_name: UI-Terminal
app_repo_path: Trading-Terminal2025/UI-Terminal-.git
app_dir: "{{ app_root }}/UI-Terminal-"
app_branch: new-infra
env_template: ui_terminal.env.j2
env_dest: "{{ app_dir }}/.env"

github_runner_enabled: true
github_runner_repo: "Trading-Terminal2025/UI-Terminal-"
github_runner_name: "{{ linux_vm_name }}-ui"
github_runner_dir_name: ui-terminal
github_runner_labels:
  - "{{ linux_vm_name }}-ui"
  - stage-tradingplatform
github_runner_registration_token: "{{ frontend_github_runner_registration_token | default('') }}"
github_runner_cleanup_legacy: []
