---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ui-terminal-secrets
  namespace: staging
spec:
  encryptedData:
    NEXT_PUBLIC_API_URL: AgCZXNTj2cVa7eYxqBqr2D2ZIHnwdKl3hE9hnuq4sp+PwvFpFy2HaaT8CIur/BAbBlSbYaJyE3diBxCWpwhGCON6dtYOIbrzTEVYeMBeLCK7Xqg28kJFMm0bWk37lx9Mz/akOsnTUGXUsLc/Oj/odgKL8X8PpG9nwfWYx0jW5lSYqxzGuFbNjABvxMMVJue6b8679iAqQZkQ9YuPLNxcD/N0Cc8qnbLPHhQE0WW5iMPiOwqQ6dOuVopsqZkKn8P5FfUezEIiifiXF20rPxQZVcTcolbAsfTmdGJwuts+dwZV1/++bxW0O/vtHOJ7UHGY1n19yuPpKoKcTdMz7XXdJiF7E7R0Q4tiTREo2dkTv7C1LwhUys9f8XmX/5UyzX+EL99uzNpGWQuRKWeD2WVkMa+eQbJ0V00Oo1FBkGBP8dCm4lRwdggk+jbUrpjJDYXxuHrRPTp+ZGn7Sg5qRLBCq3gucwBzgFAMl++l2fU3mrKjkquuxVOWKEgLmSSmRixbDJJ5aXHwFOJvtflNdOu5HI4QaUrpyJvf4ajEzuieln4ER5NwYwsNGeoZ9nmaT9i3dbReD8vf8KAw/qNs39P6xkEVXOECMLq3g1bIMSja2VZHvCuTK1DWlqIbpRY3XBEmiX5wxi+ccIdrE5oDSan6qCd5SEH0LGMGkWuOJhSfr8/Ks7B5+4mzjOu7xdbTB2Fqi7lVF9fw8s9IkNINFVJA79+DGjTxLDDItV6NTCkrTAVua4xtwQ==
    NEXT_PUBLIC_WS_URL: AgBLxoKXYV/PBMGra94R4cFIpBOKK8LxArwwcHp+Q3lSQUuf5/16JcyPpxISr9sd9Xc972500uYIPH/KGsxnSm4cV0NW/pW8jLNoBeefzGn4FZv/YVDTMCiLvX0thd4+buyqBBaQQlrbX54iYjdo3vA1p8tA6pDLXSwMQIP1CFLBF2XQoX+iDs+DIhwZW0rkJGsm+yl+vbxuUz9GjCWdbZsKSf7hxtDW3E55FKAlTJAnKdDgoMo1Mh8ezs/GfoD2Lj3aoqSQbX8eZpqXED/y2VQoAjou2Adbpi0MZLYmyvjNZZoD1eQBjce5wCBWtL3kAjQEhTxZLXBH7YDBBmT0STMtdV5LsUPKkHamYxbeElF4ArX+0ia2qjzc3pi3/D4SinANKCVgittahyptf3GQd0nR8DhDp7LAhhiW4x+BYA/kcc4QQyMlseROS3U+1uMNxyvBFZLFuJpHGQV8/yXoM55D7Vb9KNH+e40NLtnBttFA4JxdBSgqgQcs4FbTdGDoEVXlBTZqqcIb/OkglUVdZPx8kRToJm5DW7pY+SsAZgA0XCnFh2YN5v6eSc4mzFbAqXWEpGYfgsbFweMHOb6YaO+SVn1VyUfToQLMsc62kZPz70UoH8Qsn3PRCrX3A9tCHCoCtGJG8KpfE0mfVJNIs+UyrQUWqPbYqgsg+ni0dhZzvl2sOP6qb2zXa3ocurpgfpPOMPcmaYBcbEH8XH2YsXCLOpYu9doqsJ/okzJnyWeT+TjEZmU=
  template:
    metadata:
      creationTimestamp: null
      name: ui-terminal-secrets
      namespace: staging
