apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clickhouse
  namespace: infra
spec:
  interval: 1h
  chart:
    spec:
      chart: clickhouse
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: infra
  valuesFrom:
    - kind: ConfigMap
      name: clickhouse-values
