apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clickhouse-ui
  namespace: infra
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  labels:
    app: clickhouse
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - clickhouse.example.com
      secretName: clickhouse-tls
  rules:
    - host: clickhouse.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clickhouse
                port:
                  number: 8123
