---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: clickhouse-credentials
  namespace: infra
spec:
  encryptedData:
    password: AgCVpcEf0FnUxvl/595eAezNpr009DJj7P+qqWMZDbrb2us3Pj0F4CAbLqkGMe9qz33+MD2PjJ+EDYJ68udVpyh/so+7Bmnre1MIAvtWg56uE1aNCIOA6NRIp552k1b2RRsKUXOY5uWdRfsGSikvOxGZi9sm3fw3Eiq4DQznhLRtq4gcVy8hbwHjQaysbEeybct4TmTJXzLv5J3FozugcaPdD6QEQyG3S8FW9wl7bT+yjzU7fIoLEvzcV8yGUQieHBbugzpXuFApOoqOyRdO1tCer5Tp9D4eBLxGqR06SJMtE22673Rxo8gS/djKP8GJ9zNdMJelwmYne+Fg29tVkvs/MB6b1lHdyF+8E1JQh2mnLXi6mYCSmrfWhTzIvp8Eaq9puXpUjzr7Zs2pv4k2S0rUF6SKgG8K5IoylcUTzilhs68lhnEwBWkYhHmmPFEteOEoPEVgnrZCJhQA3uAJp7zlwU4dd4T2lFWY9ZBGf27qx5AoSn/vb1wLmUhOQHfzGFdlShVvFl16f2dNo1Js9vJg6L/4m05dJ89X5BjoefsDshzJy508+HY3l9PnkonDiGGTzumD8L7msk6jjrwMjxZlWejqkHMP2EZJL5fS8bZhrfOYkB/wRuUjak7l7Pv7WBcST0PH77PZeEJMF+q+BNFMGCXF5lEkY4GudzsEXAjpEa+KLpruzHnCKQNCNxLMUhU0tnLKjpbR5mDYdbui7w==
  template:
    metadata:
      creationTimestamp: null
      name: clickhouse-credentials
      namespace: infra
