# kubectl create secret generic clickhouse-credentials \
#   --namespace infra \
#   --from-literal=password=your_clickhouse_password \
#   --dry-run=client -o yaml | \
# kubeseal --format yaml > infra/clickhouse/sealedsecret.yaml

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clickhouse-credentials
  namespace: infra
spec:
  encryptedData:
    password: <sealed>
  template:
    metadata:
      name: clickhouse-credentials
      namespace: infra
