---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-credentials
  namespace: infra
spec:
  encryptedData:
    rabbitmq-password: AgCNWOiV6EzBRxnG2e/kcIxKaET399OC9Eg3UH7oq7FPpnGUg6yatOiGMaj2Ec2bRnAJeyjp0dWtTjvO7Y7Lk/LUE1INVFFt50CZ6V1FSCzz7dpdlc3UCe3dhCajvueBDZ8aZ53/ojbVahW2hyr0lG+/Pjjvxd0q+pKNqjw/gJm+ogavn+i5aeGeted5fz0H/z4/w8Lxnig09hOhicaBMOERm96vMXx2cwicTkKV3fS+BoamNqFqGDN6rSYeuwTW9IsWi8l2IUV9GS3DPAZtaSK0MxIz5CsQUBmeH+Hf7Fv031qO951fvADBd2zSQ5hcpzA57K0TCp13Smu5NJ99aVeG2hFux/Ho2/H1Md6/yUvZhM8r40dHxiVlDdQQjK19FuwUF8GDx22+o1rV0cS17SPU6GrfGSCuL4mO6zyYCdG2DPy/R+/TeQ3FI7lfIqByftcJM9+Ln5b82vKoupQhfX5wFsrKWd18FmtLjTXLUlQQsy4WVJMNoEe+Y5l4XT5ajOB1alOy2QUw4Edh3enljag2JCLxgkFDskw9h3hncx99KJfDODHiTD9QYtk5+eCieNz2K1RgRxEGYqgZ+YCs8BXyPqIJ2ADuSpZZ+Est9vNdWTJ4MPoRQHgMSDPH0tc0b70VzB4CGLehUAJINS0nJyIUylk7E6G2If9uf5vpZADGwEcN8E80wV9FDXwgy/G2EJ9YA/ZsDBSyGRbrcfp2Gyc=
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-credentials
      namespace: infra
