# kubectl create secret generic rabbitmq-credentials \
#   --namespace infra \
#   --from-literal=rabbitmq-password=your_rabbitmq_password \
#   --dry-run=client -o yaml | \
# kubeseal --format yaml > infra/rabbitmq/sealedsecret.yaml

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-credentials
  namespace: infra
spec:
  encryptedData:
    rabbitmq-password: <sealed>
  template:
    metadata:
      name: rabbitmq-credentials
      namespace: infra
