---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-credentials
  namespace: staging
spec:
  encryptedData:
    .dockerconfigjson: AgCl3+LO3TyP052LjfFjhEUMnWzwvruzYG3WEWo2wVgWfDom4IjuBgsuLUqEKsBp0ky6pJ1TmMH0XmALnLZfItsII06RVZ00rLA2Eya7Zw8yevsFIIo8PRNyw5v/fv9AgG+VLnI9X69eWZpMbtFoJErU3uXyUo1ggE1yXC+ayQvnbO0SXoXDAutpMzy03qy/8S/NqpnZ3UL4kTngcLEsBZUxl7gXXWzZCHPALKq4XhBSGBb21vyCkc6iPcY3eoL4hoYal3B6MJnpFg7YuhC3NXI+Fnm1gzWkjk5iKPWa0CKic07ijii/nSeDmdz4KD7bnc4dRO/K6r0huP8MDitrT7+FghmbLYSzNifAcX7ZPjwP+xpZaxNAb2lAnPmoWu77dnbAUEbdp+qGl5NcHve3VP7NKhY+3stweSVyqaJfgD6VLKaNObpKaJi48CgjTvD51b9cBD4XsjEMZHW+NY2eoWq73Stb/1YQZoIrA+x9Fs3q3pbbJH2bjQ3vmvPX4QHxtOWmFKxWQSrfgGiyO4N0LFa5KRxV6c4sCBY0lwi8blK3BzumqcjefOIfkEFhZXDK/pfYDiXDlxR82vd8vcY1fJoFbDj4q9VWrkvbwCEjeItmGHPFN9FFSMxRfPc9dVvS2D8sdGQnfq+J6kwth6pgzYWiCn+oXJdz4/K5vht0a4NLMJoZkByTHzOS0JwaOpCkeXsvJsUw2y60vHUYH9tC//533sAMeX0Cp3OsiKeTbGfFb7eyuNyMn9XspKLuM9+25AtziKDe16w7FvrlveIiGaVbunV1UnPYrlCYtPLAVBXfbwegY4APMt/j0p/y8+kpVZEURzwkfnE1J6/YOPKRPwcvPf9Lj6hx0Tp3Q+VTZPEtb6QAtoiw+FSlLVt5WDiZ7iw6GBnnCxnXXPs98E9PYcx1zrOl8Xh7ctQ25NiH+tZjnPDC92htWnBkpwM=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-credentials
      namespace: staging
    type: kubernetes.io/dockerconfigjson
