---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: staging
spec:
  encryptedData:
    .dockerconfigjson: AgBq/FrTCh4hLDvHKWf2lv8PaIN65DuluFIOx+DdgP6Ajej2/X50aBuWXkuCaDrIqxAw3K/eZg2ReKxXGP6cgJbJFK8xh1q8//6adUSZajSUylbTqXb6qhsaNgKMh5oStPI+ktVYQsiRCfdnH+jraAkPNjwGHBVGjT/3n08cv7WYO6gucKEZa9ZSR5yhjhxrV5KTRDV6H6+wxisduiCLtfi7w8HS1lobgNuVL46ayEvN0LNBQ6vGsNRw/O0/PKBwORI/bx2fah5Vaa+vQFuvWw+CIc8VjlRJ6welrmVw/uCndcVD8v7ORUbklk4hC+xvMwdkRO+GgBNWuy6mCONd68i//+iX947TM1ReMJ6BQnjb2+CyVf2Aur15SNW88qJphiXfjidgY91GZLYzulkhyBvDguQcW2hzauKHIT630Nmr5QeTpgQruwccwYHk6H6kANtmrCreRBWpBv64V8nHHJGNMElaeJ5n6GQZZKmi03j/6kwybB8aerRQS8vGR6vGU+ErK07N/NQRyI5iz53IoBoqu6szEsEpI4QZBeDaENJaIUYhLa0rTnCL2Fbk8uu+NWYNuzNDzMeQAsAXRk7+2E4wCU/sfHL/LtH3a8mDa3lIyIGAFdURB37rksSCwKfTCiwUPB2iqMFgyaZOxDbdKHB9zmJC59Mrv7432rbiPG10AKCQFRGgCw8lM3im0WrME0KYdkLJuBx3IaOJW822TaoUfRGSFUbaxuHBDnr/3ARFLECh4HFtL1+kJoLr+xK3Rtooyn4Nr3dUJ2SSlkCk3lMFh8PG2lnHAcikgJStsAoYbWsu+lLFoR6GHK063P5UZq/UHMv5MQCcjupl7H5JRq/R31U17fsaW1W0AYuTeqIUC5GcgqabpeIVGJeV2TgieeIqvvsFydwP9HYr1RG4aacsUu+pnYgiHimoG5WMnQA+/oYKPJbhd31lpRQ=
  template:
    metadata:
      name: ghcr-credentials
      namespace: staging
    type: kubernetes.io/dockerconfigjson
