---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgBEBcDpve3U3HNR5ontFzR4jrz5qGM+sDTvF1IhUVaBgNSgHrj9aRUtJAiNuKeR/gYSMS9OHA0j5G/9xaYB0GDVE73XV6mOJmkEprLEUh+A3j44+aIetJMwioeNPymijb4lBxyUxPxRVvdZxa0xg8yPkTzcaUDioFL4SDDfYlgIjb+WgV6ZdsKCng8IYlmK3DG7iXZuXAUf/h4sAzJ3zv5GZHRli0wc2csl5U93Sa1Zuica9R2s7b2/HDO3o2ODy7PMOu4yqNZR1vFyUbvgiG8GoCkdXIornD6psXFSJF0Jra5JBwQSHjDSq8m0WskJlDEmjIOdZLq/j3EhlJOmgULej5uKoirOQFwCRWsl21id/9CdtKpi/BJJkfz5OR22ky8Cm2j6dxUgomd5EknzqAlffscPKm6yv2gx3Qvjnq91Q6F48V6N6pgeePSn+yRJD18uEqBTM4pnJ6eU5ARPoJVbkOLTPFEmzWLJm9AMLEtDcFdgMypGuOLSCBMv9byiOfdR4DmIW5Bak+kKlB9GnZFvDyNTc/IaWgt5YAxYhC6OGRNzeSj0YeTZx15txVpCWZEI5yPmUgKdPINSkzokCUObhDmSXZQb+HhjwJJERJyiv1CI0O2oKjcEpvKKz5ZAjDrrrGy2C4HCtMjATsXoIe1CxNPCynE2OYXxxJIgIUq8cVZA0oCUbL5znE/EpOe+W3AmuBnUB7so/R2sP9JQoLDsotz+ewmiyKzDDBN8EYByCiKFnTtLCJgJg3lKSG2jgvcHs4f9uPJzZB138xxYgRHKs9pcyp2avpl1jA+MeSZxkvsHIc3kRO3jLLm3YtNMXGL2XgH8PX5bHgHTTCt71ICPmh6v2ryzqvTjIW230KCMafQYMSelyf3DY7K8fWsUKSlFp7+lUonpHultMR5TcYIyAzv3/nPCJvjhhC1gPOTOvWqI7YtTeUiT8c0=
  template:
    metadata:
      name: ghcr-credentials
      namespace: production
    type: kubernetes.io/dockerconfigjson
