---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgABJs0fM/dlVpitN0j1iX2be0hwYwymXnHd+g2Ddj0FiBgZgt38ZwYpUaRdqsVdKw/JpzwA2F2G7l7JuqbxPSWjG3WflkbIyjXNXDzLbjsSjetp9rriCYSJmOMOLAYIJhiK9219d5P4gKseY51Accx8uIkRCLHZqsfMTP86z6CIwVfBpxWyMHlOzl0aLqrQVW9vL4NuM5vJjKLaiiO1hGQWwsTsnXvDg3u65n0tT8+0/pqPJ5PNKOR6BVis2BtRZz+ENFpRreuIWna/F42FOti+BZUbRVYRJvHl0NEQUsLiby11uhXBoolXpwVAVEyFXDWC4bi231p/GcUTjnhf6vI2eV6btgJhGnX7nOzD2vTRcccVRQ+zJBYModa25jiWejQOJhLzbZ+Cz36wSQGIsPGbfKYrSGfTUhyfWGKlw28Hs1LeJMV+Urx6SPDUfRAkmToCHEK0IlLz7Xq16aKAkya2mlLou8rtzjXNwTzUgCRw89fDLbzc9V8ZPC71LCrkwd5DqPwqEtUJOgnxTPN2iccunRMVnxS+19IPOS3huaQ0rhBnShb7I2IZmPrqCJXx7lWPp+iG64PQ4IZQbfav63/00WdHdUANTztFhFcVHiFs3i6dm0hW+/aUAVW1RhVV0GaJQEVPvWbeGgMi7YjjOTnlzR662n+wVKL4yNsB73/ONlv8bzIU7xi3ClIK8R3l7Jv4+vLewKEQA1tpCSoYsoLenPfewYAE1W9rStJbMzVKYebXFI0UbBINWPhk4qhrUqqJO8i3xeDqIs5+sTUedWYMzWmheJNXiMZJVjmevHFmUmIvVG+ps0D9l/V7RcquZT0ViXWsQ2kRQ1NEhlW2J9kICemTCLrqxPP0Kvptebz8JylGaMTPZcvD0cvUyBhAjfl5RWEZWUstDXdNi9lMLHhc8S1+E7MsWMNU5lHupgmjfR/hiOu/v0edm8E=
  template:
    metadata:
      name: ghcr-credentials
      namespace: production
    type: kubernetes.io/dockerconfigjson
