---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-auth
  namespace: infra
spec:
  encryptedData:
    admin-password: AgBCgfwb6dLFsTp8nhhW5IWCq46PQPdJGpRKR5LEHxUXFm5GGD6mQTO2sOS87V9gJA+3AqXfR0ZLzmdylPg3AA9kBohLOMgUiui41pPPQ99tfg8Pz6qdWf7A8v2w9aHs3i9pE3dbXGNcCtcAF3UraRV3YQaQ+JLoZ2BrXRiCXw/u5SsqIeyKtAqANFtlwxyoapg6cVWXIglW8lAhhp2/aQEYU/kNi0Iy21pssIe13VqKXKLHy0A9eH2ZflWo9pPhOV5ix8Ah3WdplgwbH8pOs1jfy8ZwTc9cwJEC+tVSbrqRea5OYo86g1lUH84rS5+2ejs3ssuPTI5AOEL7XlU0HtAmE6cEYUNRKJWPbP1q1tj5X+O8ro7lKu2E82Chc/jyggX3HlW+czdGAEKf6s54zNphmK5dY2h7N2pTEYMnLRsUNnFfLmswVrtF/DlEjJqcOJhPEDrLzm9sMwMkmPzvxST8HEjtRY76tW9EDS3NWhs4bU/JJvuxi2pZX3ckzqwlaqUUNUPoWb5KjRimSZncIBzALcPLpmnph+1Rvi3XIvsCrl2S0tpHJ0vqyllorT4LcHjMKc4PxCoByPn67Ylm2INHCSWD5W3A681uFKHmlp0kCh5m7YFjM4+El4x5hjd/hT+CjGcPLrIQ4MfOxECsqa1qaZ4ZZfpVCI/e1T+cCot2tzOCRTon4fC16fa6U99TNA/4m+IkJS+z6hhiE/iX0cEL
    admin-user: AgCYY8spbMhuqHmOCXLpjyK1SKwM38c71yLnaZMthkXZIQCe5Xh2hiWfxKyxw2pTZ9G3xYCKpcKp0QehY2JSYfWSylQzAZWOkTQXY9mDNDaD4gH340/WMfjxw2N1Uzibx6ep8h2vWYDB47Yp4CG62xDbDxrgWAib/jxo9OwjcWo9RWlwf1rjI/fzwAyolrLpvNh8Jo3B7M4dAv0erxq0vt6XZqinaYG92pRFw5RtNnbInMB4ePym8uftKdyFUJ6wDykyz/1JdCbRvhWIrSOhiF2FbaDhDGIQWD4QNFV84ZZEJyMFamSvr4j6ySZegu/dsy/xtCqoBwnEmvA1+c56OxVFUbv1TSCDN9UG5dD6me+B5efqU5TQzSrrMCDFOcC2OHbkJP7kFS0OwMakZJ5kiyl2EvYHBU2jcXYrAvGRrwfnxl110G19ZUqmGe72cLo7OhD/dYqMrtTQHPmUO5N4Zzc6jrSikIFY7OObNyHAWJW8HWjVPxFmrmcL9Xrly1TY2mJ3/464dz+8jPe0GuAZYid/OAgD9oc7BqbyaF2HtxFHKSLII+mPBa0eiYSX9ofnUZaYlyUb+6Yp/elN7Bgx4nkspiT3j/tA5Oq28T7hUFoVXcXw02ALiLhTYMzlRqDyVDIPo67V677vNzuQUswQ4cJNFlZij6U3qtUBfpDvP2korUtAAlXnYXQyBklllGPDr1Hn37qRFw==
  template:
    metadata:
      name: grafana-auth
      namespace: infra
