all:
  children:
    linux_api:
      hosts:
        ovh-linux-api:
          ansible_host: REDACTED_VPS_IP
    linux_ui:
      hosts:
        ovh-linux-ui:
          ansible_host: REDACTED_VPS_IP
    linux_dashboard:
      hosts:
        ovh-linux-dashboard:
          ansible_host: REDACTED_VPS_IP
    workers:
      hosts: {}
