---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ui-terminal-secrets
  namespace: production
spec:
  encryptedData:
    NEXT_PUBLIC_API_URL: AgA2IcdfL10YZosf1SBIC+Fh1jbFi4c/zQVegbAGVYWM1IbGoyq+PnW5q+26hkiGKs6X/rCsY7n6S04rpEe2du2/k7/sVonNU6VetAQqPkA1sDLzk1dBsBtHmUKE3ERVMhYarXp1OtCsj46yAn9GxbIQAg+BEPOeiz8MLeewPypycH9Rgnf1pQAEBeD29p0CWvK0sI/FEAAziXx0NaHJgJvIWUw281qWq3s+C3DXe5L7V+fOb1yd/HfSaMAUPjxOUrsEqy2+6dQIEodIFAzAtQBVecijfjMn+ILCGBjoj5CT+AAOqUCmooItgVFuwix+YrvvCgHvEwV7p/snj7pizMqEAolJrncsZ/ckqPRQxtaVhOELBW0eEbVH2GC+KRrZlxl1nzrOWwZuh+uSEPsoYTD9323XPs4g93ZxlhomIuWXHAvXEfHrJUFIvgvSUM+KcbIjawf7jZAaH+Xhc3IQzCsTzyERDYzzCZX5/GcZsku3qvxlte434H2X99/BSEYs4VBKqvxt5DxrbI6uwgj6xkIXIJEyzoFUyLrmy1cOAOXPdVn+gnL8YMgC8I+TPQ1tIMehviE8oS2nwiIO1fvwwM6ZMLrewsDJIF4nqmQagXEi69ouR+I4z2WmxbVq9Fh/rPWZ94gROHTZUJPG2z7TKHeJgAYNkkRj8jBfOpVDh0Tsg8m96n2lWfKiTw+65O2B/aTjs4ZccJcHbgEL/u/pL+4bAs1TsuEYGVT+pJW11Ky8dt24kw==
    NEXT_PUBLIC_WS_URL: AgBtss5ofPfeF2O2vk5uwEA6JGomc9+zYzadR0/qNiOqZA4LtRxFg4jX0fQ/Oxj65lPLLsFP5KsoKQcw1WLR7yt9Mcoc3PfZb3MF47W/PkJS1pikKnYvzUe0vMPqp1vnO49dr2JENOih0cDXkyYKpCHExVEm/7Tqw/lmuuITn/QSgGDCRzd90NH0S1ZA1mccy0mDRH5NZbX1/uR/2Riug/YPaj/xMZiqQDGAj6GuYHLrniDVSpFjynOeT41fWfsEzTQxqu82i7/dEFxOUr6VK1TOSZ1lI3oYQMdOErH811Ew8d48HnbasSgsVnr2/9jdyRTXXb/zDUrlsjKEr/3+/4+KSwEV8N1TOCLxYDxhmhn6U6AorspaOO2gllc9GeS89bD4IU4uAAHggSZ6jlf8S/AzMgniKh9kCuoF4YUX32NWHU9kmTg/7EsWNzteudmV3sGOwvQxKp4urYVgZ4SImKuY0xN+5QZLlj15kPrd9HidcaWCvbDAPEiXO/lucGzpGi+VT/W5rGfNyHFqlIWz81NFTr1ymMSYeeotzk8kq46/KrDeZTZGudE1+GdsoCKIRGm8p6cdzjNeLTinz4FCHArzr5G/zFD+/aH+f6ABwzBcZMbR+81RJ9DmtGhXeiQe2bx78fnsdpbISvgtAho7Ay59//C3ix8j72jz8ugtLYQwhrmTHQ0YAntV20Rzh1dGBbSkzowHW4ik2z0t2rxypyjAWoC+Ml5qGN5TeJKC23TxyRFdXBA=
  template:
    metadata:
      creationTimestamp: null
      name: ui-terminal-secrets
      namespace: production
