name: Validate GitOps Manifests

on:
  push:
    branches: [main, develop-infra]
  pull_request:
    branches: [main, develop-infra]

jobs:

  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML
        run: |
          cat > /tmp/.yamllint.yml << 'EOF'
          extends: default
          rules:
            document-start: disable
            line-length: disable
          EOF
          yamllint -c /tmp/.yamllint.yml gitops/

  validate-k8s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install kubeconform
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/download/v0.6.4/\
          kubeconform-linux-amd64.tar.gz | tar xz
          mv kubeconform /usr/local/bin/

      - name: Validate Kubernetes manifests
        run: |
          find gitops/ -name "*.yaml" ! -name "values.yaml" ! -name "sealedsecret.yaml" | xargs kubeconform \
            -strict \
            -ignore-missing-schemas \
            -schema-location default \
            -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'

  validate-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform fmt check
        run: terraform fmt -check -recursive terraform/

      - name: Terraform validate
        working-directory: terraform/ovh
        run: |
          terraform init -backend=false
          terraform validate

  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          extra_args: --only-verified
