# Generated by Terraform — do not edit by hand. Re-run terraform apply to refresh.
# Three logical inventory hosts on aws_instance.linux_vm (UI, API, dashboard runner).
all:
  vars:
    ansible_user: ${linux_ssh_user}
%{ if ssh_key_path != "" ~}
    ansible_ssh_private_key_file: "${ssh_key_path}"
%{ endif ~}
    ansible_ssh_common_args: "-o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new"
  children:
    linux_ui:
      hosts:
        ${linux_vm_name}-ui:
          ansible_host: ${linux_public_ip}
    linux_api:
      hosts:
        ${linux_vm_name}-api:
          ansible_host: ${linux_public_ip}
    linux_dashboard:
      hosts:
        ${linux_vm_name}-dashboard:
          ansible_host: ${linux_public_ip}
